export const excluded = [
    "wrap",
    "window",
    "see through",
    "perforated",
    "graphics",
    "back",
    "customized",
    "contour cut",
    "decal",
    "vinyl",
    'a',
    'the',
    'of',
    'and',
    'to',
    'in',
    'is',
    'you',
    'that',
    'it',
    'he',
    'was',
    'for',
    'on',
    'are',
    'as',
    "above", "across", "against", "along", "among", "around", "at", "before", "behind", "below", "beneath", "beside", "between", "by", "down", "from", "into", "near", "off", "toward", "under", "upon", "with", "within"
]